// React-Minesweeper/src/root.tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import configStore from './store/configStore'
import Board from './components/Board'
import TopBar from './components/TopBar'

const store = configStore()

ReactDOM.render(
    <Provider store={store}>
        <div style={{display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <TopBar/>
            <Board/>
        </div>
    </Provider>,
    document.getElementById("root")
)

// Vue-Minesweeper/src/components/Root.vue
<template>
    <div :class="[{root: true}]">
        <TopBar/>
        <Board/>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'
import TopBar from './TopBar.vue'
import Board from './Board.vue'

export default Vue.extend({
    name: 'Root',
    components: {
        TopBar,
        Board
    }
})
</script>

<style scoped>
.root {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>
