// Angular/src/components/topBar/topBar.component.ts
import { Component } from '@angular/core'
import { BeginnerDifficulty, IntermediateDifficulty, ExpertDifficulty } from '../../model'
import { Store as NgrxStore } from '@ngrx/store'
import { Store } from '../../store/store'

@Component({
  selector: 'TopBar',
  templateUrl: './topBar.component.html',
  styleUrls: ['./topBar.component.css'],
})

export class TopBarComponent {

    constructor(private store: NgrxStore<Store>){
    }
    resetGame() {
        this.store.dispatch({ type: ""})
        //dispatchResetGameAction(this.$store.dispatch)
    }
    setBeginnerDifficulty(){
         this.store.dispatch({ type: ""})
        //dispatchSetDifficultyAction(new BeginnerDifficulty())(this.$store.dispatch)
    }
    setIntermediateDifficulty() {
        this.store.dispatch({ type: ""})
        //dispatchSetDifficultyAction(new IntermediateDifficulty())(this.$store.dispatch)
    }
    setExpertDifficulty() {
        this.store.dispatch({ type: ""})
        //dispatchSetDifficultyAction(new ExpertDifficulty())(this.$store.dispatch)
    }

}

// Vue-Minesweeper/src/components/TopBar.vue
<template>
    <div>
        <button id="reset-game-button" v-on:click="resetGame" :class="[{button: true}]">
          Reset
        </button>
        <button id="set-beginner-difficulty-button" v-on:click="setBeginnerDifficulty" :class="[{button: true}]">
          Beginner
        </button>
        <button  id="set-intermediate-difficulty-button" v-on:click="setIntermediateDifficulty" :class="[{button: true}]">
          Intermediate
        </button>
        <button  id="set-expert-difficulty-button" v-on:click="setExpertDifficulty" :class="[{button: true}]">
          Expert
        </button>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { dispatchResetGameAction } from '../actions/resetGame'
import { dispatchSetDifficultyAction } from '../actions/setDifficulty'
import { BeginnerDifficulty, IntermediateDifficulty, ExpertDifficulty } from '../model'

export default Vue.extend({
    name: 'TopBar',
    methods: {
        resetGame() {
            dispatchResetGameAction(this.$store.dispatch)
        },
        setBeginnerDifficulty(){
            dispatchSetDifficultyAction(new BeginnerDifficulty())(this.$store.dispatch)
        },
        setIntermediateDifficulty() {
            dispatchSetDifficultyAction(new IntermediateDifficulty())(this.$store.dispatch)
        },
        setExpertDifficulty() {
            dispatchSetDifficultyAction(new ExpertDifficulty())(this.$store.dispatch)
        }
    }
})
</script>

<style scoped>
 .button {
     margin: 16px;
     font-size: 20px;
 }
</style>
