// React/src/components/Cell.tsx
import * as React from 'react'
import { Position, CellType } from '../model/index'

function getColor(type : CellType) {
  if (type === CellType.None) return 'grey'
  if (type === CellType.Mine) return 'red'
  return 'yellow'
}

function getNumber(type : CellType) {
  if (type === CellType.OneMineClose) return '1'
  if (type === CellType.TwoMinesClose) return '2'
  if (type === CellType.TreeMinesClose) return '3'
  if (type === CellType.FourMinesClose) return '4'
  if (type === CellType.FiveMinesClose) return '5'
  if (type === CellType.SixMinesClose) return '6'
  if (type === CellType.SevenMinesClose) return '7'
  if (type === CellType.EightMinesClose) return '8'
  return ''
}

const Cell = function Cell(props: { position: Position, type: CellType, clickAction : Function }) {
    const color = getColor(props.type)
    const number = getNumber(props.type)
    const clickAction = props.type === CellType.None ? () => props.clickAction() : () => {}
    return (
      <div onClick={clickAction} style={{ display:'flex', alignItems: 'center', justifyContent: 'content', width: '40px', height: '40px', backgroundColor: color, borderBlockColor: 'black', borderStyle: 'solid', borderWidth: '1px'}}>
        <div>{number}</div>
      </div>
    )
  }
  
export default Cell

// Vue/src/components/Cell.vue
<template>
  <div @click="clickAction"  :class="[{cell: true}, {mineColor: isMine}, {noneColor: isNone}, {otherColor: isOther}]">
    <div>{{getNumber}}</div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Position, CellType } from '../model'

export default Vue.extend({
  name: 'Cell',
  props: {
    position: { type: Position, required: true },
    type: { type: Number, required: true }
  },
  methods: {
    clickAction(){
      this.$emit('cellCliked', [this.$props.position, this.$props.type])
    }
  },
  computed: {
    isMine() {
      return this.type === CellType.Mine
    },
    isNone() {
      return this.type === CellType.None
    },
    isOther() {
      return this.type != CellType.None && this.type != CellType.Mine
    },
    getNumber() {
      if (this.type === CellType.OneMineClose) return '1'
      if (this.type === CellType.TwoMinesClose) return '2'
      if (this.type === CellType.TreeMinesClose) return '3'
      if (this.type === CellType.FourMinesClose) return '4'
      if (this.type === CellType.FiveMinesClose) return '5'
      if (this.type === CellType.SixMinesClose) return '6'
      if (this.type === CellType.SevenMinesClose) return '7'
      if (this.type === CellType.EightMinesClose) return '8'
      return ''
    }
  }
})
</script>

<style scoped>
  .mineColor { background-color: red; }
  .noneColor { background-color: grey; }
  .otherColor { background-color: yellow; }
  .cell {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 40px;
    height: 40px;
    border-color: black;
    border-style: solid;
    border-width: 1px;
  }
</style>
