// Vue-Minesweeper/src/components/TopBar.vue
<template>
    <div>
        <button id="reset-game-button" v-on:click="resetGame" :class="[{button: true}]">
          Reset
        </button>
        <button id="set-beginner-difficulty-button" v-on:click="setBeginnerDifficulty" :class="[{button: true}]">
          Beginner
        </button>
        <button  id="set-intermediate-difficulty-button" v-on:click="setIntermediateDifficulty" :class="[{button: true}]">
          Intermediate
        </button>
        <button  id="set-expert-difficulty-button" v-on:click="setExpertDifficulty" :class="[{button: true}]">
          Expert
        </button>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { dispatchResetGameAction } from '../actions/resetGame'
import { dispatchSetDifficultyAction } from '../actions/setDifficulty'
import { BeginnerDifficulty, IntermediateDifficulty, ExpertDifficulty } from '../model'

export default Vue.extend({
    name: 'TopBar',
    methods: {
        resetGame() {
            dispatchResetGameAction(this.$store.dispatch)
        },
        setBeginnerDifficulty(){
            dispatchSetDifficultyAction(new BeginnerDifficulty())(this.$store.dispatch)
        },
        setIntermediateDifficulty() {
            dispatchSetDifficultyAction(new IntermediateDifficulty())(this.$store.dispatch)
        },
        setExpertDifficulty() {
            dispatchSetDifficultyAction(new ExpertDifficulty())(this.$store.dispatch)
        }
    }
})
</script>

<style scoped>
 .button {
     margin: 16px;
     font-size: 20px;
 }
</style>

// React/src/components/TopBar.tsx
import * as React from 'react'
import { useDispatch } from 'react-redux'
import { createResetGameAction } from '../actions/resetGame'
import { createDistpatchSetDifficultyAction } from '../actions/setDifficulty'
import { BeginnerDifficulty, IntermediateDifficulty, ExpertDifficulty } from '../model/index'

const TopBar  = () => {
    const dispatch = useDispatch()
    return (
      <div>
        <button key="reset-game-button" onClick={() => dispatch(createResetGameAction())} style={{ margin: "16px", fontSize: "20px" }}>
          Reset
        </button>
        <button key="set-beginner-difficulty-button" onClick={() => createDistpatchSetDifficultyAction(new BeginnerDifficulty())(dispatch)} style={{ margin: "16px", fontSize: "20px" }}>
          Beginner
        </button>
        <button  key="set-intermediate-difficulty-button" onClick={() => createDistpatchSetDifficultyAction(new IntermediateDifficulty())(dispatch)} style={{ margin: "16px", fontSize: "20px" }}>
          Intermediate
        </button>
        <button  key="set-expert-difficulty-button" onClick={() => createDistpatchSetDifficultyAction(new ExpertDifficulty())(dispatch)} style={{ margin: "16px", fontSize: "20px" }}>
          Expert
        </button>
      </div>
    )
  }

  export default TopBar
